USE upf_riders;

/* Primer fem els delete de les dades de les taules (en ordre invers a la seva creació) */

DELETE FROM serve
WHERE business_id <> 0 AND headquarters_code <> 0;

DELETE FROM business
WHERE id <> 0;

DELETE FROM category
WHERE category_id <> 0;

DELETE FROM uses
WHERE vehicle_ref_number <> 0 AND headquarters_code <> 0;

DELETE FROM licensed
WHERE rider_id <> 0 AND vehicle_type_id <> 0;

DELETE FROM vehicle
WHERE ref_number <> 0;

DELETE FROM vehicle_type
WHERE type_id <> 0;

DELETE FROM rider
WHERE rider_id <> 0;

DELETE FROM headquarters
WHERE code <> 0;

/* Ara inserim les dades a les taules en el mateix ordre de la creació de les taules */


-- Inserts en headquarters
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (1, 41.4038, 2.14205, "CL BALMES 351, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (2, 41.3985, 2.15017, "CL MARIA CUBI 39, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (3, 42.0994, 1.84562, "PS DE LA PAZ 39, BERGA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (4, 41.4091, 2.15426, "CL TRAVESSERA DE DALT 44, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (5, 41.3897, 2.15713, "CL MALLORCA 193, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (6, 41.374, 2.11968, "CL PROGRES 86, L'HOSPITALET DE LLOBREGAT, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (7, 41.3859, 2.16584, "CL PELAI 3, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (8, 41.4725, 2.08326, "CL SANTIAGO RUSINYOL 30, SANT CUGAT DEL VALLÈS, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (9, 41.3892, 2.17402, "RD SANT PERE 22, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (10, 41.3839, 2.17393, "CL PORTAFERRISSA 34, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (11, 41.4097, 2.1748, "CL INDUSTRIA 158, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (12, 41.396, 2.15407, "CL DE BALMES 176, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (13, 41.3888, 2.13003, "AV DIAGONAL 601, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (14, 41.3753, 2.138, "CL CARRER DE SANTS 56, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (15, 41.3935, 2.14518, "CL CALVET 2, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (16, 41.4016, 2.15341, "CL GRAN DE GRACIA 138, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (17, 41.3879, 2.16992, "RB DE CATALUNYA 87, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (18, 41.3836, 2.16395, "RD SANT ANTONI 82, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (19, 41.3622, 2.13241, "CL GRAN VIA DE LAS CORTS CATALANES 632, BARCELONA, BARCELONA");
INSERT INTO headquarters(code, latitude, longitude, postal_address) VALUES (20, 41.3821, 2.16978, "CL CARME 38, BARCELONA, BARCELONA");


-- Inserts en rider
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (1, "Ramon Coromines", 1);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (2, "Joan Riera", 1);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (3, "Jordi Cassini", 1);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (4, "Manel Junqueres", 2);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (5, "Jonathan Vereda", 2);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (6, "Francisco Reina", 3);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (7, "Carles Castro", 4);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (8, "Manuel Gabriel González Ramos", 4);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (9, "Manuel Valcárcel Iniesta", 5);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (10, "Juan Gil Gutiérrez", 5);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (11, "Santiago Cabañero Masip", 6);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (12, "Álvaro María Nadal Belda", 6);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (13, "Francisco Molinero Hoyos", 6);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (14, "José Miguel Molla Nieto", 6);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (15, "Juan Vicente Oltra Panadero", 7);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (16, "Antonio Agustín Yeste Martínez", 7);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (17, "Gustavo Téllez Soriano", 7);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (18, "Francisco Serrano Alarcón", 7);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (19, "Carlos Abiétar Picazo", 8);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (20, "Emilio García García", 8);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (21, "Macario Gallego Granados", 9);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (22, "Gerardo Camps Devesa", 9);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (23, "Santiago Martínez Rodríguez", 9);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (24, "José López Garrido", 9);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (25, "José Rafael Sáez Sánchez", 10);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (26, "Marcos Zaragoza Mayor", 11);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (27, "Antoni Roderic i Tost", 11);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (28, "Robert Quereda Amorós", 11);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (29, "Ernest Blasco Riquelme", 12);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (30, "Javier Martínez Salcedo", 12);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (31, "Cristian Santiago De Jesús", 12);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (32, "Daniel Simón Plá", 13);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (33, "Marcelino Torre Canto", 14);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (34, "Josep Paré Aregall", 14);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (35, "Carles Cuerva Claver", 14);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (36, "Joan Canongia Gerona", 15);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (37, "Germán Rodríguez Sánchez", 15);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (38, "Albert Soler Sicilia", 15);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (39, "José Zaragoza Alonso", 15);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (40, "Joan Rangel Tarrés", 15);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (41, "Daniel Fernández González", 16);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (42, "Marcelino Marcos Líndez", 16);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (43, "Adrián Barbón Rodríguez", 17);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (44, "Julio Garzón González", 17);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (45, "Glòria Mans Cervantes", 17);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (46, "Alberto Matallanas Carrillo", 18);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (47, "Albert Iglesias Boza", 18);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (48, "José Luis Ayllón Manso", 18);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (49, "Antonio Gallego Burgos", 18);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (50, "Daniel Serrano Coronado", 18);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (51, "Pedro Calviño Carmona", 18);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (52, "Fernando Llombart Guilabert", 19);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (53, "Manuel Conde García", 19);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (54, "Pedro Alonso Navarro", 19);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (55, "M.ª José Díaz Algarin", 19);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (56, "José Manuel López González", 19);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (57, "Manuel Gallardo Martínez", 20);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (58, "David Zambrana Lorenzo", 20);
INSERT INTO rider(rider_id, name, headquarters_code) VALUES (59, "Diego Sánchez Simón", 20);


-- Inserts en vehicle_type
INSERT INTO vehicle_type( type_id, description, number_of_wheels ) VALUES ( 1, "Ciclomotor", 2 );
INSERT INTO vehicle_type( type_id, description, number_of_wheels ) VALUES ( 2, "Moto", 2 );
INSERT INTO vehicle_type( type_id, description, number_of_wheels ) VALUES ( 3, "Cotxe", 4 );
INSERT INTO vehicle_type( type_id, description, number_of_wheels ) VALUES ( 4, "Furgoneta", 4 );
INSERT INTO vehicle_type( type_id, description, number_of_wheels ) VALUES ( 5, "Camió petit", 4 );
INSERT INTO vehicle_type( type_id, description, number_of_wheels ) VALUES ( 6, "Camió gran", 6 );
INSERT INTO vehicle_type( type_id, description, number_of_wheels ) VALUES ( 7, "Bicicleta", 2 );


-- Inserts en licensed
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (1 , 1 , 3);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (1 , 3 , 2);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (1 , 7 , 10);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (2 , 1 , 8);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (2 , 7 , 5);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (3 , 1 , 5);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (4 , 3 , 6);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (4 , 4 , 2);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (4 , 5 , 4);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (5 , 6 , 10);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (6 , 2 , 7);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (7 , 1 , 3);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (8 , 1 , 10);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (6 , 3 , 4);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (6 , 4 , 6);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (6 , 5 , 1);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (6 , 6 , 1);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (3 , 2 , 2);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (12 , 5 , 4);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (12 , 6 , 10);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (13 , 6 , 7);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (14 , 4 , 3);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (14 , 1 , 10);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (14 , 7 , 12);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (15 , 3 , 4);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (15 , 7 , 15);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (16 , 4 , 6);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (16 , 5 , 1);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (16 , 6 , 1);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (17 , 4 , 2);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (18 , 5 , 4);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (19 , 6 , 10);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (20 , 2 , 7);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (21 , 1 , 3);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (22 , 1 , 10);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (22 , 3 , 4);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (23 , 4 , 6);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (24 , 5 , 1);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (25 , 6 , 1);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (25 , 4 , 2);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (26 , 5 , 4);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (26 , 3 , 10);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (27 , 4 , 7);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (27 , 1 , 3);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (28 , 1 , 10);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (29 , 3 , 4);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (30 , 4 , 6);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (31 , 5 , 1);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (31 , 6 , 1);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (32 , 4 , 2);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (33 , 5 , 4);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (34 , 6 , 10);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (35 , 6 , 7);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (36 , 1 , 3);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (37 , 1 , 10);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (37 , 3 , 4);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (37 , 4 , 6);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (38 , 5 , 1);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (38 , 6 , 1);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (39 , 4 , 2);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (40 , 5 , 4);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (41 , 6 , 10);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (42 , 3 , 7);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (43 , 5 , 7);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (43 , 1 , 3);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (45 , 3 , 2);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (46 , 1 , 8);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (47 , 1 , 5);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (47 , 3 , 6);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (48 , 4 , 2);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (48 , 5 , 4);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (49 , 6 , 10);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (50 , 6 , 7);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (51 , 6 , 7);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (51 , 1 , 3);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (51 , 3 , 2);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (52 , 1 , 8);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (53 , 1 , 5);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (54 , 3 , 6);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (54 , 4 , 2);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (54 , 5 , 4);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (55 , 6 , 10);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (56 , 5 , 7);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (57 , 4 , 7);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (58 , 1 , 3);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (58 , 3 , 2);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (59 , 2 , 8);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (59 , 1 , 5);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (9 , 3 , 4);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (10 , 4 , 6);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (10 , 5 , 1);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (11 , 6 , 1);
INSERT INTO licensed(rider_id, vehicle_type_id, years_experience) VALUES (59 , 3 , 2);


-- Inserts en vehicle
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (1, "Seat", "Ibiza", 200, 3);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (2, "Seat", "Altea", 300, 3);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (3, "Renault", "Clio", 100, 3);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (4, "Renault", "Scenic", 300, 3);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (5, "Volkswagen", "Polo", 150, 3);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (6, "Volkswagen", "Golf", 250, 3);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (7, "Fiat", "Punto", 200, 3);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (8, "Renault", "Kangoo", 500, 4);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (9, "Renault", "Traffic", 800, 4);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (10, "Hyosung", "SF50", 10, 1);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (11, "Hyosung", "SB50M", 10, 1);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (12, "Honda", "Dylan", 40, 2);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (13, "Kymco", "Dink 125 LX", 40, 2);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (14, "Kymco", "Dink 125 LX", 45, 2);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (15, "Renault", "Maxity", 1000, 5);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (16, "Mitsubishi", "Canter", 1000, 5);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (17, "Nissan", "Cabstar", 1000, 5);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (18, "Renault", "Midlum", 3000, 6);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (19, "Ford", "Fiesta", 250, 3);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (20, "Fiat", "Panda", 200, 3);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (21, "Kymco", "People", 40, 2);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (22, "Kymco", "Super 9", 40, 2);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (23, "Kymco", "Grand Dink", 45, 2);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (24, "Kymco", "Grand Dink", 40, 2);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (25, "Toyota", "Dyna", 1000, 5);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (26, "Honda", "Bali", 45, 2);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (27, "Peugeot", "207", 200, 3);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (28, "Canyon", "Ultimate", 15, 7);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (29, "BH", "OverX", 15, 7);
INSERT INTO vehicle(ref_number, brand, model, liter_capacity, vehicle_type_id) VALUES (30, "Cannondale", "Lefty9", 15, 7);


-- Inserts en uses
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (1, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (2, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (6, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (7, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (8, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (10, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (11, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (12, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (13, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (14, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (15, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (16, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (17, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (18, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (6, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (7, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (20, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (8, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (10, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (21, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (22, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (23, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (24, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (15, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (25, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (16, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (6, 3);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 3);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (21, 3);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (22, 3);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (13, 3);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (14, 3);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (15, 3);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (25, 3);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (18, 3);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (1, 4);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (2, 4);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 4);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 4);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (7, 4);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (20, 4);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 4);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (10, 4);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (11, 4);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (12, 4);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (23, 4);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (24, 4);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (13, 4);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (14, 4);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (1, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (2, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (20, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (7, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (8, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (12, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (26, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (21, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (22, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (23, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (24, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (13, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (14, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (15, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (2, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (1, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (27, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (6, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (7, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (20, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (8, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (10, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (12, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (26, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (21, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (22, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (23, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (24, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (25, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (16, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (17, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (18, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (1, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (2, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (6, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (7, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (20, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (8, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (10, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (21, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (22, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (23, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (24, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (16, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (17, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (18, 7);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 8);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 8);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 8);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (20, 8);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (7, 8);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (8, 8);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 8);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (10, 8);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (11, 8);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (12, 8);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (26, 8);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (13, 8);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (14, 8);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (15, 8);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (25, 8);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (1, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (27, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (6, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (12, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (26, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (21, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (22, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (23, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (24, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (15, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (25, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (16, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (17, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (18, 9);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (7, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (20, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (8, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (10, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (11, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (12, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (26, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (21, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (23, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (24, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (13, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (14, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (15, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (25, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (16, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (17, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (18, 10);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (2, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (1, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (27, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (6, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (8, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (10, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (11, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (12, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (26, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (21, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (22, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (23, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (24, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (13, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (14, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (17, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (18, 11);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (2, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (1, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (27, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (10, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (11, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (12, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (26, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (13, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (14, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (15, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (25, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (16, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (17, 12);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (6, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (7, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (20, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (8, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (10, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (11, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (12, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (26, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (21, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (22, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (23, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (24, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (13, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (14, 13);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (2, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (1, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (27, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (6, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (11, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (12, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (26, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (21, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (22, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (23, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (24, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (13, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (14, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (15, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (25, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (16, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (17, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (18, 14);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (1, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (2, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (27, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (6, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (7, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (20, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (8, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (10, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (11, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (12, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (26, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (21, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (22, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (23, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (24, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (13, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (14, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (15, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (25, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (16, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (17, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (18, 15);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (6, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (7, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (20, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (8, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (12, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (26, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (21, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (22, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (23, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (24, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (16, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (17, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (18, 16);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (2, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (1, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (27, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (6, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (7, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (20, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (10, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (11, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (12, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (26, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (21, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (22, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (23, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (24, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (13, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (14, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (15, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (17, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (18, 17);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (2, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (1, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (27, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (6, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (7, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (20, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (10, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (11, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (12, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (13, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (14, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (15, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (25, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (16, 18);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (6, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (7, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (20, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (8, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (9, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (26, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (21, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (22, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (23, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (24, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (13, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (14, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (15, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (25, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (16, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (17, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (18, 19);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (2, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (1, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (27, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (3, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (4, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (19, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (5, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (6, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (22, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (23, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (24, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (13, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (14, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (15, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (25, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (16, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (17, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (18, 20);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (28, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (29, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (30, 1);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (28, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (29, 2);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (30, 3);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (28, 3);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (28, 4);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (30, 5);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (29, 6);
INSERT INTO uses(vehicle_ref_number, headquarters_code) VALUES (30, 6);


-- Inserts en category
INSERT INTO category(category_id, description, parent_category_id) VALUES (1, "Restaurant", NULL);
INSERT INTO category(category_id, description, parent_category_id) VALUES (2, "Perruqueria", NULL);
INSERT INTO category(category_id, description, parent_category_id) VALUES (3, "Restaurant Rus", 1);
INSERT INTO category(category_id, description, parent_category_id) VALUES (4, "Restaurant Italià", 1);
INSERT INTO category(category_id, description, parent_category_id) VALUES (5, "Perruqueria unisex", 2);
INSERT INTO category(category_id, description, parent_category_id) VALUES (6, "Perruqueria canina", 2);
INSERT INTO category(category_id, description, parent_category_id) VALUES (7, "Restaurant Rus siberia", 3);
INSERT INTO category(category_id, description, parent_category_id) VALUES (8, "Farmacia", NULL);
INSERT INTO category(category_id, description, parent_category_id) VALUES (9, "Drogueria", NULL);
INSERT INTO category(category_id, description, parent_category_id) VALUES (10, "Telefonia", NULL);
INSERT INTO category(category_id, description, parent_category_id) VALUES (11, "Telefonia movil", 10);
INSERT INTO category(category_id, description, parent_category_id) VALUES (12, "Advocat", NULL);
INSERT INTO category(category_id, description, parent_category_id) VALUES (13, "Dentista", NULL);
INSERT INTO category(category_id, description, parent_category_id) VALUES (14, "Llibreria", NULL);
INSERT INTO category(category_id, description, parent_category_id) VALUES (15, "Llibreria infantil", 14);
INSERT INTO category(category_id, description, parent_category_id) VALUES (16, "Tecnologia", NULL);
INSERT INTO category(category_id, description, parent_category_id) VALUES (17, "Ordinadors", 16);
INSERT INTO category(category_id, description, parent_category_id) VALUES (18, "Electrodomestics", 16);


-- Inserts en business
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (1, "El Romero", 41.4336, 2.17169, "NULL", 3);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (2, "Comes", 41.4337, 2.15057, "NULL", 2);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (3, "Cristal", 41.4468, 2.19521, "NULL", 1);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (4, "Puma", 41.399, 2.15401, "NULL", 4);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (5, "Pelos", 41.4178, 2.17735, "NULL", 2);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (6, "PC 100", 41.418, 2.12826, "NULL", 17);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (7, "White Smile", 41.4329, 2.12894, "NULL", 13);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (8, "Mirall", 41.4111, 2.20516, "NULL", 18);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (9, "Vives", 41.3652, 2.15023, "NULL", 5);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (10, "Pelucas", 41.3941, 2.12654, "NULL", 6);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (11, "Vivaldi", 41.4103, 2.11212, "NULL", 5);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (12, "Kastixov", 41.4157, 2.12208, "NULL", 7);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (13, "Merce", 41.4142, 2.15916, "NULL", 9);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (14, "Doctor Fleming", 41.409, 2.17667, "NULL", 8);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (15, "Tissores", 41.4041, 2.13409, "NULL", 2);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (16, "La llei", 41.3961, 2.17186, "NULL", 12);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (17, "Celulars", 41.4211, 2.19933, "NULL", 11);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (18, "Telefons", 41.4291, 2.21786, "NULL", 10);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (19, "Conectats", 41.3745, 2.13375, "NULL", 11);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (20, "Fa fred", 41.3799, 2.1159, "NULL", 7);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (21, "Blancs", 41.3928, 2.11143, "NULL", 13);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (22, "Roma", 41.3943, 2.13375, "NULL", 4);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (23, "Ben sa", 41.3928, 2.15126, "NULL", 8);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (24, "Drogueria Vicente", 41.3827, 2.15298, "NULL", 9);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (25, "Siberia", 41.3732, 2.16534, "NULL", 7);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (26, "Bon can", 41.4054, 2.19452, "NULL", 6);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (28, "Estetics", 41.3956, 2.19898, "NULL", 5);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (29, "Guauu", 41.4098, 2.21992, "NULL", 6);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (30, "Harashov", 41.3969, 2.18388, "NULL", 3);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (31, "Bon look", 41.3894, 2.17907, "NULL", 5);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (32, "Doctor Mestres", 41.3812, 2.18044, "NULL", 8);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (33, "Limpio", 41.3912, 2.19864, "NULL", 9);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (34, "Bon apetit", 41.4144, 2.16637, "NULL", 1);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (35, "Moscu", 41.4293, 2.16328, "NULL", 3);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (36, "El petit princep", 41.3647, 2.12585, "NULL", 15);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (37, "Resplandor", 41.3619, 2.17186, "NULL", 13);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (38, "La maquina", 41.382, 2.17255, "NULL", 18);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (39, "Corto Circuito", 41.4126, 2.1492, "NULL", 16);
INSERT INTO business(id, name, latitude, longitude, address, category_id) VALUES (40, "La jungla", 41.4412, 2.22267, "NULL", 15);


-- Inserts en serve
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (7, 3, 1594.03);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (6, 3, 964.353);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (12, 3, 735.296);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (11, 3, 1317.42);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (35, 4, 1958.92);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (2, 4, 793.324);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (7, 4, 1168.99);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (13, 5, 1586.26);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (2, 5, 1654.98);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (39, 5, 1045.39);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (15, 5, 1916.89);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (7, 5, 1777.67);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (6, 5, 1172.88);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (12, 5, 1737.4);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (4, 6, 1000.03);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (23, 6, 1179.1);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (39, 6, 1412.3);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (15, 6, 769.062);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (22, 6, 1031);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (10, 6, 1525.09);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (9, 7, 773.982);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (19, 7, 1214.57);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (36, 7, 1261.09);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (37, 8, 638.838);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (25, 8, 979.277);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (9, 8, 1235.11);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (32, 9, 1395.49);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (31, 9, 1347.92);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (38, 9, 742.827);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (16, 9, 1438.02);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (25, 9, 1259.09);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (4, 9, 1823.17);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (24, 9, 965.729);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (23, 9, 1425.79);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (30, 10, 1639.92);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (31, 10, 1741.91);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (14, 10, 1319.24);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (16, 10, 788.725);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (34, 10, 1495.54);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (13, 10, 1541.43);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (4, 10, 943.743);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (23, 10, 1465.28);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (39, 10, 1844.05);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (1, 11, 555.482);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (35, 11, 847.455);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (2, 11, 1355.19);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (17, 12, 1790.3);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (3, 12, 1341.8);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (1, 12, 1517.33);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (40, 13, 843.608);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (18, 13, 1007.06);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (3, 13, 1856.17);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (29, 14, 1049.66);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (18, 14, 1199.04);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (8, 14, 1171.85);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (17, 14, 1348.41);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (29, 15, 1103.31);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (8, 15, 1328.65);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (28, 15, 1369.83);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (33, 15, 1663.66);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (26, 15, 1676.88);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (8, 16, 1947.61);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (28, 16, 886.158);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (33, 16, 1130.14);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (26, 16, 902.925);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (30, 16, 461.125);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (31, 16, 1298.04);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (14, 16, 1566.42);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (16, 16, 1454.34);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (8, 17, 1679.04);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (17, 17, 865.73);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (26, 17, 1697.56);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (5, 17, 1007.87);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (14, 17, 1607.9);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (34, 17, 1992.89);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (5, 18, 1063.24);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (14, 18, 1571.73);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (1, 18, 1600.6);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (34, 18, 643.034);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (35, 18, 1037.32);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (13, 18, 820.803);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (2, 18, 1933.45);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (39, 18, 1558.04);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (19, 19, 1771.61);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (22, 19, 1892.84);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (10, 19, 1455.62);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (20, 19, 401.096);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (21, 19, 1107.01);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (24, 20, 1003.93);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (23, 20, 1368.61);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (19, 20, 1140.18);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (22, 20, 1375.48);
INSERT INTO serve(business_id, headquarters_code, distance) VALUES (10, 20, 1704.93);